### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [joshuacurl/tc359-project4#1]
I'm actually getting an error in the JavaScript console, which is keeping the Bootstrap JS from successfully initializing.

> Uncaught Error: Bootstrap's JavaScript requires jQuery

Can you check this out and see if you can resolve it? Let me know when you have or if you need help.

**Comment by joshuacurl** [comment]
Should be fixed!

**Comment by chrisvfritz** [comment]
:+1: Looks good.

## Points of improvement for future projects

### Unused `index.html`

It looks like there's an unused `index.html` file in your views folder. Since it's no longer needed, it's best to just delete it to keep our project from becoming cluttered.

If you you did delete it locally and are surprised that it's still on GitHub, then try running this line before your next commit:

``` bash
git add -A .
```

That will add not only file additions and modifications, but also file deletions. I know, it's strange that you need a special parameter for this, but you do.
